baseURL = "/"
publishDir = "../"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Paál Gyula - Tutorial Series"
theme = "hugo-theme-learn"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/paalgyula/paalgyula.github.io/edit/master/site-source/content/"
  description = "Paal Gyula's public knowledgebase based on 11years work experience"
  author = "Paál Gyula"
  showVisitedLinks = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/paalgyula/paalgyula.github.io"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

